### ISSUE TITLE
403 Client Error when loading the model

### ISSUE THREAD

**Issue by gennsev** [gretelai/gretel-tools#2]
Hello,

I am trying to replicate your Demo code,

```
from gretel_tools import headers
h = headers.HeaderAnalyzer()
```
but right on the first part, I have this error message:
`403 Client Error: Forbidden for url: https://gretel-tools.s3-us-west-2.amazonaws.com/FT_headers.bin.gz`

I wonder if your model is still open source and where I can download it.
Also, I was thinking about using the similarity check in a project, and for reliability reasons, it would be better to have those headers deployed with the system instead of downloading on each use case. Is there a way to do it with your current open-source code?

**Comment by johntmyers** [comment]
Hi @gennsev sorry for the delay but I just updated the repo. Please note Python 3.7+ is required, if you look at the demo Notebook you'll see that the `model_file` path can be a path to the model on disk now. The updated URL to the model is in the `headers.py` module.
